### ISSUE TITLE
北大老哥您好

### ISSUE THREAD

**Issue by Water2style** [zhixuanli/semantic-segmentation-pytorch#2]
最近刚开始做语义分割复现，您收集的代码都是能用的吗

**Comment by zhixuanli** [comment]
还没收集完，代码能用，但是各有各的问题。正在头疼中试图解决他们

**Comment by zhixuanli** [comment]
主要问题就是，这些代码运行后无法达到他们声称的性能……正在检查是怎么回事 @Water2style

**Comment by Water2style** [comment]
> 主要问题就是，这些代码运行后无法达到他们声称的性能……正在检查是怎么回事 @Water2style

哎天，我也是，复现了一个FCN，miou跑了300轮只有30%.我还是个小白，不知道以后能否给您发邮件请教请教

**Comment by zhixuanli** [comment]
您好，30%应该是哪里还有问题，不只是作者故意不公布参数的问题

我也刚开始做不久，多互相交流吧，别客气
